### ISSUE TITLE
Error: Shader compilation error for shader 5: 0:9(8): error: unrecognized layout identifier `set'

### ISSUE THREAD

**Issue by richardh538** [LesleyLai/GLGrassRenderer#1]
Hi

Error: Shader compilation error for shader 5: 0:9(8): error: unrecognized layout identifier `set'

What does this error mean?

**Comment by LesleyLai** [comment]
Sorry for the late reply! I think it was my mistake, and since I only tested this code on Nvidia driver (which doesn't manifest this issue), the bug got overlooked. I updated the code to remove all references to `set` in the shaders.
